inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "gems/vendor/**/*"
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/config.ru"
    - "**/*.gemspec"
    - "gems/*/.simplecov"
    - "gems/*/bin/**"
    - "gems/*/config/**"
    - "gems/*/db/**/*"
    - "gems/*/test/dummy/bin/*"
    - "gems/*/test/dummy/config/**/*"
    - "gems/*/test/dummy/db/**/*"
    - "gems/*/**/templates/*"
    - "gems/tasks/*"

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 150

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Lint/ConstantDefinitionInBlock:
  Exclude:
    - gems/*/test/**/*.rb

Metrics/ClassLength:
  Max: 102

Metrics/MethodLength:
  Max: 12

Naming/FileName:
  Exclude:
    - gems/rubocop-rhino-project/lib/rubocop-rhino-project.rb

Style/ClassAndModuleChildren:
  Exclude:
    - gems/*/test/**/*.rb
    - gems/*/app/overrides/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringConcatenation:
  Exclude:
    - "gems/*/test/test_helper.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

###
# rubocop-minitest specific
###

Minitest/MultipleAssertions:
  Max: 5

###
# rubocop-rails specific
###

# Present/blank will fight each other otherwise
Rails/Blank:
  UnlessPresent: false
