source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.6'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.0'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.6'

# Use Sass to process CSS
gem "sassc-rails"

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'dalli'

gem 'sendgrid-ruby'
gem 'sendgrid-actionmailer'

gem 'google_drive'

group :development, :test do
  gem 'debug'
  gem 'openapi3_parser'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'brakeman'
  gem 'railroady'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'dotenv-rails'
gem 'pg'
gem 'letter_opener', :group => :development

group :development, :test do
  gem 'factory_bot'
  gem 'factory_bot_rails'

  # These are aligned with rails 7.0
  gem 'rubocop', '1.24.1', require: false
  gem 'rubocop-packaging', '0.5.1', require: false
  gem 'rubocop-performance', '1.13.1', require: false
  gem 'rubocop-minitest', '0.17.0', require: false
  gem 'rubocop-rails', '2.13.0', require: false
  gem 'rubocop-rhino-project', '~> 0.20.0.beta.108', require: false

  gem 'ffaker'
  gem 'simplecov', require: false
  gem 'webmock', require: false
end

gem 'arctic_admin'
gem 'activeadmin_addons'

gem 'rollbar'

gem "rhino_project", "~> 0.20.0.beta.108"

gem "rhino_project_core", "~> 0.20.0.beta.108"

gem "rhino_project_organizations", "~> 0.20.0.beta.108"

gem "rhino_project_notifications", "~> 0.20.0.beta.108"

gem "rhino_project_subscriptions", "~> 0.20.0.beta.108"

gem "rhino_project_jobs", "~> 0.20.0.beta.108"
