require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-factory_bot
  - rubocop-rhino-project

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**"
    - "config/**/*"
    - "db/migrate/*"
    - "db/schema.rb"
    - "log/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "**/Gemfile"

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 150

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Metrics/BlockLength:
  Exclude:
    - "app/admin/**"

Metrics/ClassLength:
  Max: 102

Metrics/MethodLength:
  Max: 12

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
    - test/channels/application_cable/connection_test.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - ".simplecov"
    - "**/Rakefile"
    - "**/config.ru"

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

###
# rubocop-minitest specific
###

Minitest/MultipleAssertions:
  Max: 5

###
# rubocop-rails specific
###

# Present/blank will fight each other otherwise
Rails/Blank:
  UnlessPresent: false

# Don't force locales usage
Rails/I18nLocaleTexts:
  Enabled: false
