# Loosely based on https://betterprogramming.pub/rails-6-development-with-docker-55437314a1ad
networks:
  development:
volumes:
  db_data:
  redis_data:
  gem_cache:
  node_cache:
  shared_data:
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      # Don't mix node_modules between host and container
      - node_cache:/app/node_modules
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    stdin_open: true
    tty: true
    init: true
    entrypoint: ./bin/dev-docker-entrypoint.sh
    # Just keep the backend open
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '${PORT:-3000}']
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_URL: redis://redis:6379/${REDIS_DATABASE:-0}
      VITE_RUBY_HOST: vite
    healthcheck:
      test: 'curl -f http://localhost:${PORT:-3000}/admin/login || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
      start_interval: 5s
    depends_on:
      - db
      - redis
  vite:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      backend:
        condition: service_healthy
    entrypoint: ./bin/dev-vite-entrypoint.sh
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    init: true
    networks:
      - development
    ports:
      - '3036:3036'
    volumes:
      - .:/app
      # Don't mix node_modules between host and container
      - node_cache:/app/node_modules
      - gem_cache:/usr/local/bundle/gems
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - development
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - 5432
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - development
    ports:
      - 6379
