default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  ssl_params:
    # https://guides.rubyonrails.org/action_cable_overview.html#redis-adapter for Heroku
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
  channel_prefix: <%= "#{Rails.application.class.module_parent_name.underscore}_production" %>
