# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "minitest", ">= 5.15.0", "< 5.22.0"

# We need a newish Rake since Active Job sets its test tasks' descriptions.
gem "rake", ">= 13"

gem "sprockets-rails", ">= 2.0.0"
gem "propshaft", ">= 0.1.7"
gem "capybara", ">= 3.39"
gem "selenium-webdriver", ">= 4.11.0"

gem "rack-cache", "~> 1.2"
gem "stimulus-rails"
gem "turbo-rails"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "importmap-rails", ">= 1.2.3"
gem "dartsass-rails"
# require: false so bcrypt is loaded only when has_secure_password is used.
# This is to avoid Active Model (and by extension the entire framework)
# being dependent on a binary library.
gem "bcrypt", "~> 3.1.11", require: false

# This needs to be with require false to avoid it being automatically loaded by
# sprockets.
gem "terser", ">= 1.1.4", require: false

# Explicitly avoid 1.x that doesn't support Ruby 2.4+
gem "json", ">= 2.0.0", "!=2.7.0"

# Workaround until Ruby ships with cgi version 0.3.6 or higher.
gem "cgi", ">= 0.3.6", require: false

gem "prism"

group :lint do
  gem "syntax_tree", "6.1.1", require: false
end

group :rubocop do
  gem "rubocop", ">= 1.25.1", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-packaging", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-md", require: false

  # This gem is used in Railties tests so it must be a development dependency.
  gem "rubocop-rails-omakase", require: false
end

group :mdl do
  gem "mdl", "!= 0.13.0", require: false
end

# Core
gem "activeadmin", "~> 2.14.0"
gem 'analytics-ruby', '~> 2.0.0', :require => 'segment/analytics'
gem 'rack-cors', :require => 'rack/cors'
gem 'devise_token_auth', git: 'https://github.com/lynndylanhurley/devise_token_auth.git', ref: '5b1a5e19450f3755ce5ebe2f631b40c876ffc22d'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-azure-activedirectory-v2'
gem 'omniauth-auth0'
gem "omniauth-rails_csrf_protection"
gem 'pundit'
gem 'arel-helpers'
gem 'rgl'
gem 'pg_search'
gem 'acts-as-taggable-on', '~> 9.0'
gem 'phonelib'
gem 'ancestry'
gem 'js_regex'
gem 'countries'

# Organizations
gem 'devise_invitable', '2.0.6'

# Jobs
gem 'resque', '2.6.0'
gem 'resque-scheduler', '4.10.2'
gem 'resque-heroku-signals', '2.6.0'
gem 'active_scheduler', '0.7.0'

# Notifications
gem 'activity_notification', '2.2.3'

group :development, :test do
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'openapi3_parser'
  gem 'webmock', require: false
end

gem "useragent", require: false

# Add your own local bundler stuff.
local_gemfile = File.expand_path(".Gemfile", __dir__)
instance_eval File.read local_gemfile if File.exist? local_gemfile

group :test do
  gem "minitest-bisect", require: false
  gem "minitest-ci", require: false
  gem "minitest-retry"

  platforms :mri do
    gem "stackprof"
    gem "debug", ">= 1.1.0", require: false
  end

  # Needed for Railties tests because it is included in generated apps.
  gem "brakeman"
end

platforms :ruby, :windows do
  gem "nokogiri", ">= 1.8.1", "!= 1.11.0"

  # Needed for compiling the ActionDispatch::Journey parser.
  gem "racc", ">=1.4.6", require: false

  # Active Record.
  group :db do
    gem "pg", "~> 1.3"
  end
end

gem "tzinfo-data", platforms: [:windows, :jruby]
gem "wdm", ">= 0.1.0", platforms: [:windows]
