# Gemfile
source 'https://rubygems.org'
gemspec

eval_gemfile('../Gemfile')

# Core
gem "activeadmin", "~> 2.14.0"
gem 'analytics-ruby', '~> 2.0.0', :require => 'segment/analytics'
gem 'rack-cors', :require => 'rack/cors'
gem 'devise_token_auth', git: 'https://github.com/lynndylanhurley/devise_token_auth.git', ref: '5b1a5e19450f3755ce5ebe2f631b40c876ffc22d'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-azure-activedirectory-v2'
gem 'omniauth-auth0'
gem "omniauth-rails_csrf_protection"
gem 'pundit'
gem 'arel-helpers'
gem 'rgl'
gem 'pg_search'
gem 'acts-as-taggable-on', '~> 9.0'
gem 'phonelib'
gem 'ancestry'
gem 'countries'

# Organizations
gem 'devise_invitable', '2.0.9'

# Jobs
gem 'resque', '2.6.0'
gem 'resque-scheduler', '4.10.2'
gem 'resque-heroku-signals', '2.6.0'
gem 'active_scheduler', '0.7.0'

# Notifications
gem 'activity_notification', '2.2.3'
