# frozen_string_literal: true

require "rake/testtask"
require 'rdoc/task'

task default: :test

task :package

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'RhinoJobs'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include('README.md')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

Rake::TestTask.new do |t|
  t.pattern = "test/**/*_test.rb"
  t.warning = true
  t.verbose = true
end
